[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "djangorestframework>=3.18.1",
    "google-genai>=2.28.0",
    "gunicorn>=26.2.0",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.4",
    "whitenoise>=6.12.0",
]
